import { DocumentData, QueryDocumentSnapshot, SnapshotOptions } from "@angular/fire/firestore";

export class Personal {

  /* Forma corta de crear un modelo en typescript */
  constructor(
    public uid: string,
    public id: number,
    public id_company: number,
    public id_asset_location: number,
    public id_account: number,
    public id_custom_field_group: number,
    public custom_fields_groups_description: string,
    public path_image: string,
    public code: string,
    public first_name: string,
    public last_name: string,
    public email: string,
    public saved_configuration_table: boolean,
    public active: string,
    public creation_date: string,
    public address: string,
    public city: string,
    public state: string,
    public zip_code: string,
    public country: string,
    public latitude: string,
    public longitud: string,
    public telephone: string,
    public telephone_2: string,
    public sms: string,
    public id_group_2: number,
    public id_group_1: number,
    public id_hourly_rate: string,
    public asset_location_description: string,
    public hourly_rates_description: string,
    public groups_1_description: string,
    public groups_2_description: string,
    public id_assets_location: string,
    public account_item_description: string,
    public account_email: string,
    public id_language: string,
    public only_request: boolean,
    public id_group_permission: number,
    public groups_permissions_description: string,
    public account_active: string,
    public belongs: string,
    public psw: string,
    public name: string,
    public id_work_shift: string,
    public description_work_shifts: string,
    public type_user: string,
    public full_name: string,
    public custom_fields_values: string,
    public path_signature: string,
    public description: string,
    public hourly_rate_cost: string,
    public id_collaborator: string,
    public is_active_collaborator: string,

  ){}
}


// Firestore data converter
export const PersonalConverter = {
  toFirestore: (user: Personal) => {
      return {
        "uid": user.uid,
        "id": user.id,
        "id_company": user.id_company,
        "id_asset_location": user.id_asset_location,
        "id_account": user.id_account,
        "id_custom_field_group": user.id_custom_field_group,
        "custom_fields_groups_description": user.custom_fields_groups_description,
        "path_image": user.path_image,
        "code": user.code,
        "first_name": user.first_name,
        "last_name": user.last_name,
        "email": user.email,
        "saved_configuration_table": user.saved_configuration_table,
        "active": user.active,
        "creation_date": user.creation_date,
        "address": user.address,
        "city": user.city,
        "state": user.state,
        "zip_code": user.zip_code,
        "country": user.country,
        "latitude": user.latitude,
        "longitud": user.longitud,
        "telephone": user.telephone,
        "telephone_2": user.telephone_2,
        "sms": user.sms,
        "id_group_2": user.id_group_2,
        "id_group_1": user.id_group_1,
        "id_hourly_rate": user.id_hourly_rate,
        "asset_location_description": user.asset_location_description,
        "hourly_rates_description": user.hourly_rates_description,
        "groups_1_description": user.groups_1_description,
        "groups_2_description": user.groups_2_description,
        "id_assets_location": user.id_asset_location,
        "account_item_description": user.account_item_description,
        "account_email": user.account_email,
        "id_language": user.id_language,
        "only_request": user.only_request,
        "id_group_permission": user.id_group_permission,
        "groups_permissions_description": user.groups_permissions_description,
        "account_active": user.account_active,
        "belongs": user.belongs,
        "psw": user.psw,
        "name": user.name,
        "id_work_shift": user.id_work_shift,
        "description_work_shifts": user.description_work_shifts,
        "type_user": user.type_user,
        "full_name": user.full_name,
        "custom_fields_values": user.custom_fields_values,
        "path_signature": user.path_signature,
        "description": user.description,
        "hourly_rate_cost": user.hourly_rate_cost,
        "id_collaborator": user.id_collaborator,
        "is_active_collaborator": user.is_active_collaborator
          };
  },
  fromFirestore: (snapshot: QueryDocumentSnapshot<DocumentData>,
                  options: SnapshotOptions) => {
      const data = snapshot.data(options);
      return new Personal(
        data['uid'],
        data['id'],
        data['id_company'],
        data['id_asset_location'],
        data['id_account'],
        data['id_custom_field_group'],
        data['custom_fields_groups_description'],
        data['path_image'],
        data['code'],
        data['first_name'],
        data['last_name'],
        data['email'],
        data['saved_configuration_table'],
        data['active'],
        data['creation_date'],
        data['address'],
        data['city'],
        data['state'],
        data['zip_code'],
        data['country'],
        data['latitude'],
        data['longitud'],
        data['telephone'],
        data['telephone_2'],
        data['sms'],
        data['id_group_2'],
        data['id_group_1'],
        data['id_hourly_rate'],
        data['asset_location_description'],
        data['hourly_rates_description'],
        data['groups_1_description'],
        data['groups_2_description'],
        data['id_assets_location'],
        data['account_item_description'],
        data['account_email'],
        data['id_language'],
        data['only_request'],
        data['id_group_permission'],
        data['groups_permissions_description'],
        data['account_active'],
        data['belongs'],
        data['psw'],
        data['name'],
        data['id_work_shift'],
        data['description_work_shifts'],
        data['type_user'],
        data['full_name'],
        data['custom_fields_values'],
        data['path_signature'],
        data['description'],
        data['hourly_rate_cost'],
        data['id_collaborator'],
        data['is_active_collaborator'],
        );
  }
};
